version: '3'
services: 
    smartpresenter:
        build:
            context: .
            args: 
                - PORT=9000
        ports: 
            - "9000:9000"
        networks: 
            - defaultgw
networks: 
    defaultgw: